source: /module
destination: /var/site
theme: docs-theme
data_dir : docs/_data

disable_disk_cache: true
livereload: true

permalink: /:categories/:title/  # Generate correct urls based on file path

# Strict error checking
liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

relative_links:
  enabled:     true
  collections: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

plugins:
  - jekyll-ditaa
  - jekyll-relative-links
  - include-generated
  - menu-support

ditaa_debug_mode: false
ditaa_output_directory: /var/ditaa

kramdown:
  math_engine: katex
  math_engine_opts: {}
